GET http://localhost:3000/reminders/63ce5b92299bb98bc4ddd3e6

###

POST http://localhost:3000/reminders
Content-Type: application/json

{
    "name": "abc",
    "content": "abcdef",
    "data": "2016-05-18T16:00:00Z",
    "istodo": true
}

###

DELETE http://localhost:3000/reminders/63ce6a2d18e90c2d802bcfc9

###

PATCH http://localhost:3000/reminders/63ce5b92299bb98bc4ddd3e6
Content-Type: application/json

{
    "name": "fumo",
    "content": "fumo"
}

###